### ISSUE TITLE
rake aborted! 'development' database is not configured. Available: ["production"]

### ISSUE THREAD

**Issue by Ankidoo** [olemskoi/redmine_centosadmin_rating#10]
Добрый день, решил попробовать установить ваш плагин.
когда делаю rake redmine:plugins:migrate
вываливает ошибку:
rake aborted!
ActiveRecord::AdapterNotSpecified: 'development' database is not configured. Available: ["production"]
и т.д...

**Comment by Ankidoo** [comment]
решил пойти чуть по-другому:
bundle exec rake redmine:plugins NAME=bundle exec rake redmine:plugins NAME=redmine_centosadmin_rating RAILS_ENV=production RAILS_ENV=production
Migrating redmine_centosadmin_rating (Redmine Centos-admin.ru Rating plugin)...
== 1 CreateCentosRatings: migrating ===========================================
-- create_table(:centos_ratings)
   -> 0.0441s
-- add_index(:centos_ratings, :evaluated_id)
   -> 0.0767s
-- add_index(:centos_ratings, :evaluator_id)
   -> 0.0748s
-- add_index(:centos_ratings, :issue_id)
   -> 0.0748s
-- add_index(:centos_ratings, :project_id)
   -> 0.0747s
-- add_index(:centos_ratings, :created_on)
   -> 0.0747s
== 1 CreateCentosRatings: migrated (0.4207s) ==================================

== 2 AddMustRateSendedToIssues: migrating =====================================
-- add_column(:issues, :must_rate_sended, :boolean, {:default=>false, :null=>false})
   -> 0.8946s
== 2 AddMustRateSendedToIssues: migrated (0.8948s) ============================

== 3 RenameCentosRatingsToStaffRatings: migrating =============================
-- rename_table(:centos_ratings, :staff_ratings)
   -> 0.6486s
== 3 RenameCentosRatingsToStaffRatings: migrated (0.6488s) ====================

rake aborted!
Don't know how to build task 'exec' (see --tasks)
/usr/local/share/gems/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/usr/local/share/gems/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/share/gems/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/share/gems/gems/bundler-1.15.2/lib/bundler/cli/exec.rb:27:in `run'
/usr/local/share/gems/gems/bundler-1.15.2/lib/bundler/cli.rb:360:in `exec'
/usr/local/share/gems/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/share/gems/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/share/gems/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
/usr/local/share/gems/gems/bundler-1.15.2/lib/bundler/cli.rb:20:in `dispatch'
/usr/local/share/gems/gems/bundler-1.15.2/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
/usr/local/share/gems/gems/bundler-1.15.2/lib/bundler/cli.rb:10:in `start'
/usr/local/share/gems/gems/bundler-1.15.2/exe/bundle:30:in `block in <top (required)>'
/usr/local/share/gems/gems/bundler-1.15.2/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/usr/local/share/gems/gems/bundler-1.15.2/exe/bundle:22:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)


Но все равно получил ошибку =(

**Comment by Ankidoo** [comment]
чуть по-другому вроде сработало:
bundle exec rake redmine:plugins NAME=redmine_centosadmin_rating RAILS_ENV=production
